spring:
  application:
    name: user-service
  liquibase:
    enabled: true
    dropFirst: true
    changeLog: classpath:/db/changelog/db-changelog-master.yml
    parameters:
      spring.datasource.driver-class-name: ${org.postgresql.Driver}
      spring.datasource.url: ${DB_URL:jdbc:postgresql://localhost:5432/users}
      spring.datasource.username: ${postgres}
      spring.datasource.password: ${admin}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/users}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:admin}
eureka:
  instance:
    appname: user-service
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8085
